openapi: '3.0.2'
info:
  version: '1.0'
  title: API Title
  description: API Description
  termsOfService: 'https://api.server.test/terms'
  contact:
    name: API Support
    email: victor@gmail.com
servers:
  - url: https://api.server.test/v1
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
