"""Inicial

Revision ID: 3c0e298deafd
Revises: 
Create Date: 2024-04-11 16:45:16.211289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0e298deafd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_exame',
    sa.Column('tipo_exame', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_login',
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_vacina',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('proposito', sa.String(), nullable=False),
    sa.Column('ml', sa.Float(), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.Column('vencimento', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_auxiliar',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('funcao', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('credencial', sa.String(), nullable=True),
    sa.Column('id_login', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_login'], ['tb_login.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_medico',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('crm', sa.String(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('especialidade', sa.String(), nullable=False),
    sa.Column('id_login', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_login'], ['tb_login.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_paciente',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('sexo', sa.String(), nullable=False),
    sa.Column('dt_nasc', sa.DateTime(), nullable=False),
    sa.Column('contato', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id_login', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_login'], ['tb_login.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_procedimento',
    sa.Column('procedimento', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_cirurgia',
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_procedimento', sa.Integer(), nullable=True),
    sa.Column('id_auxiliar', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_auxiliar'], ['tb_auxiliar.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['tb_procedimento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_prontuario',
    sa.Column('prontuario', sa.String(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_procedimento', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['tb_procedimento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_agenda',
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('dia', sa.DateTime(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_procedimento', sa.Integer(), nullable=True),
    sa.Column('id_cirurgia', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cirurgia'], ['tb_cirurgia.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['tb_procedimento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_consulta',
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_agenda', sa.Integer(), nullable=True),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.Column('id_prontuario', sa.Integer(), nullable=True),
    sa.Column('id_procedimento', sa.Integer(), nullable=True),
    sa.Column('id_exame', sa.Integer(), nullable=True),
    sa.Column('id_vacina', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_agenda'], ['tb_agenda.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_exame'], ['tb_exame.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['tb_procedimento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_prontuario'], ['tb_prontuario.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vacina'], ['tb_vacina.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pagamento',
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_exame', sa.Integer(), nullable=True),
    sa.Column('id_consulta', sa.Integer(), nullable=True),
    sa.Column('id_cirurgia', sa.Integer(), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cirurgia'], ['tb_cirurgia.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_consulta'], ['tb_consulta.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_exame'], ['tb_exame.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pagamento')
    op.drop_table('tb_consulta')
    op.drop_table('tb_agenda')
    op.drop_table('tb_prontuario')
    op.drop_table('tb_cirurgia')
    op.drop_table('tb_procedimento')
    op.drop_table('tb_paciente')
    op.drop_table('tb_medico')
    op.drop_table('tb_auxiliar')
    op.drop_table('tb_vacina')
    op.drop_table('tb_login')
    op.drop_table('tb_exame')
    # ### end Alembic commands ###
