"""titulo da migração

Revision ID: 8004c26e5328
Revises: 
Create Date: 2024-04-10 19:25:35.783403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8004c26e5328'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_consulta',
    sa.Column('id_paciente', sa.BigInteger(), nullable=True),
    sa.Column('id_agenda', sa.BigInteger(), nullable=True),
    sa.Column('id_medico', sa.BigInteger(), nullable=True),
    sa.Column('id_prontuario', sa.BigInteger(), nullable=True),
    sa.Column('id_procedimento', sa.BigInteger(), nullable=True),
    sa.Column('id_exame', sa.BigInteger(), nullable=True),
    sa.Column('id_vacina', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_agenda'], ['tb_agenda.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_exame'], ['tb_exame.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medico'], ['tb_medico.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_procedimento'], ['tb_procedimento.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_prontuario'], ['tb_prontuario.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vacina'], ['tb_vacina.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_pagamento',
    sa.Column('id_paciente', sa.BigInteger(), nullable=True),
    sa.Column('id_exame', sa.BigInteger(), nullable=True),
    sa.Column('id_consulta', sa.BigInteger(), nullable=True),
    sa.Column('id_cirurgia', sa.BigInteger(), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_create', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_cirurgia'], ['tb_cirurgia.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_consulta'], ['tb_consulta.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_exame'], ['tb_exame.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_paciente'], ['tb_paciente.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_pagamento')
    op.drop_table('tb_consulta')
    # ### end Alembic commands ###
